name: Build, test, and publish

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build_test_and_publish:
    runs-on: ubuntu-latest
    steps:
    - id: install_net_core
      name: Install .Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.103'

    - id: cache_nuget
      name: Cache NuGet
      uses: actions/cache@v1
      with:
        path: ~/.nuget/bin
        key: ${{ runner.os }}-nuget-bin

    - id: install_nuget
      name: Install NuGet
      if: steps.cache_nuget.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/.nuget/bin
        wget https://dist.nuget.org/win-x86-commandline/v5.4.0/nuget.exe -O ~/.nuget/bin/nuget.exe

    - id: checkout_repository
      name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - id: fetch_repository
      name: Fetch repository for GitVersion
      run: |
        if [[ "$(git rev-parse --is-shallow-repository)" == 'true' ]]; then
          git fetch --no-recurse-submodules --prune --unshallow
        else
          git fetch --no-recurse-submodules --prune
        fi

    - id: cache_nuget_packages
      name: Cache NuGet packages
      uses: actions/cache@v1
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-packages-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-packages-

    - id: restore_nuget_packages
      name: Restore NuGet packages
      run: mono ~/.nuget/bin/nuget.exe restore -LockedMode
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_NUGET }}

    - id: build_solution
      name: Build solution
      run: dotnet build --no-restore --configuration Release

    - id: test_solution
      name: Test solution
      run: |
        dotnet test --no-build --configuration Release /property:GenerateCoverageReport=false
        if [[ -f 'coverage.xml' ]]; then
            echo '##[set-output name=coverage_exist;]true'
        else
            echo '##[set-output name=coverage_exist;]false'
        fi

    - id: upload_code_coverage
      name: Upload code coverage
      if: steps.test_solution.outputs.coverage_exist == 'true'
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.TOKEN_CODECOV }}
        file: coverage.xml
        fail_ci_if_error: true

    - id: package_libraries
      name: Package libraries
      if: github.event_name == 'push'
      run: |
        dotnet pack --no-build --configuration Release --output packages
        if [[ "$(ls -1 packages 2> /dev/null | wc -l)" == '0' ]]; then
            echo '##[set-output name=packages_exist;]false'
        else
            echo '##[set-output name=packages_exist;]true'
        fi

    - id: push_packages
      name: Push packages
      if: github.event_name == 'push' && steps.package_libraries.outputs.packages_exist == 'true'
      run: |
        mono ~/.nuget/bin/nuget.exe push packages/*.nupkg -ConfigFile Boilerplate/csharp/NuGet.config -Source github.com -SkipDuplicate
        mono ~/.nuget/bin/nuget.exe push packages/*.snupkg -ConfigFile Boilerplate/csharp/NuGet.config -Source github.com -SkipDuplicate
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_NUGET }}
